import React from 'react'
import '../Cart/Cart.css'

function Cart() {
    return (<div className='Cart'>
        <div className='Cart_Heading'>
            <div className='Cart_Heading_Title'>
                <h1>Title</h1>
                <h6>Auther</h6>
            </div>
        </div>
        <div className='Cart_Body'>
            <h3>BLOG 1</h3>

            <p>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus, reiciendis placeat? Ratione fugit velit, et facere odio quaerat quo iste, pariatur asperiores error ab? Facere ratione laborum eaque placeat magni.
                                                                                                                Labore, illo aliquid expedita nesciunt aut animi sunt perspiciatis blanditiis similique maiores, maxime, sint libero tempore praesentium tenetur vitae ex quisquam consequuntur? Laborum libero excepturi accusantium! Sapiente consequuntur esse officia.
                                                                                                                Laboriosam, neque ducimus! Odio reiciendis quas ratione veniam distinctio repellendus debitis iure praesentium! Rerum officiis voluptatem incidunt pariatur aliquam? Esse magnam voluptate officia recusandae labore laudantium quasi pariatur autem impedit.
                                                                                                                Esse harum eveniet iure! Aliquid numquam libero, quas rem vel dolorum esse, natus fugiat consequatur sequi officiis commodi dicta aperiam exercitationem accusantium est praesentium velit impedit labore consectetur architecto itaque?
                                                                                                                A, labore ipsam repellat quidem, error iste, porro quas vel praesentium hic qui officia ipsa voluptate enim fugiat nesciunt excepturi recusandae est at! Possimus hic minus recusandae doloremque? Incidunt, veritatis.
                                                                                                                Distinctio libero ullam autem harum totam quaerat earum aspernatur, incidunt eaque corporis natus porro iure quidem consequatur explicabo et, ipsa eligendi ex neque quasi exercitationem vitae officia impedit! Provident, inventore?
                                                                                                                Ratione, veritatis minus quasi maxime explicabo rerum dolore tenetur! Cumque, illum et commodi, molestiae neque aspernatur dolorum, sed tenetur dignissimos sequi labore alias sit eum quia cum maiores in ullam!
                                                                                                                Iste consectetur accusantium neque. Quos laudantium reprehenderit, nobis quod dolorem voluptas aliquam amet a aspernatur illo asperiores corporis pariatur nulla culpa natus quisquam voluptate atque alias sapiente! Aliquid, incidunt distinctio?
                                                                                                                Inventore, fugiat neque accusamus voluptatum quod, quis ab magnam illum, autem corrupti quasi fugit sequi eos aspernatur distinctio! Numquam praesentium, delectus reprehenderit sed officia ullam eius quas cumque error nulla?
                                                                                                                Aliquam, iusto accusamus. Velit sit et repellat quibusdam quod aut. Cumque quibusdam nihil earum eos modi autem ipsa sed, minima unde aut, repellat tempore enim dolorum quasi sapiente, provident dolorem!
                                                                                                                Omnis inventore explicabo cumque! Deleniti molestiae deserunt facilis, at ipsam, repellat placeat recusandae reprehenderit aliquid voluptatibus dolor similique ipsum est quidem dolore voluptatem sequi quis! Doloribus expedita ipsa neque tenetur?
                                                                                                                Dolorem aut eaque, in enim tempore esse exercitationem quam repellendus dolor, eveniet sapiente nobis dolorum recusandae odit ipsa alias consequatur. Tempora placeat iusto a error alias accusantium, quibusdam libero. Rem!
                                                                                                                Deleniti, accusamus laudantium rerum numquam quis reiciendis, assumenda suscipit atque, velit dignissimos aperiam eligendi ullam? Unde ea minima, rerum eligendi est obcaecati eos odit animi, explicabo minus earum rem placeat?
                                                                                                                Odit ut dignissimos architecto eveniet repellendus veniam culpa incidunt, sed commodi voluptates obcaecati iure eius sapiente ea nostrum fuga voluptatum molestiae minima impedit maxime. Consequuntur similique dolorem recusandae ab vitae.
                                                                                                                Odit nobis iste atque obcaecati molestias, omnis explicabo distinctio quam recusandae asperiores laborum ut consectetur laboriosam. Recusandae maiores, placeat accusantium fuga saepe dolorem pariatur, tenetur expedita odio voluptatem, voluptatibus quos.
                                                                                                                Doloribus possimus magnam officiis aliquam reprehenderit, facilis accusamus ea voluptatum? Incidunt aliquid facere doloremque magni corrupti quia quod, libero iusto? Odit voluptates fugiat et tempora autem alias non adipisci ea?
                                                                                                                Consequatur dolores amet quia. Odio ipsum sed optio tempora reprehenderit doloribus molestiae. Placeat, hic cumque expedita sequi molestiae incidunt molestias eveniet voluptas ab at dolorem possimus, earum harum numquam quidem.
                                                                                                                Consequatur suscipit cupiditate repellat ad, vero delectus recusandae placeat amet, magnam, enim architecto est assumenda? Placeat ipsum quas vitae maiores, nam beatae reprehenderit, voluptas corporis totam, alias assumenda cumque sapiente.
                                                                                                                Ipsa, molestias mollitia optio quibusdam est architecto! Corporis illum facilis vel debitis vero, minus placeat, veritatis eum quos maxime voluptatum eveniet quis? Deleniti, temporibus ullam atque ex fugit itaque quaerat.
                                                                                                                Atque, non! Labore corporis vel pariatur, sint ab asperiores iusto possimus veritatis minima neque totam tempora saepe qui sequi. Dignissimos expedita earum nemo rerum quibusdam veniam similique! Tenetur, odit fugiat.
                                                                                                                Doloribus voluptatibus at sunt minima odio incidunt illo veritatis excepturi commodi? Porro sequi est eaque, molestias repudiandae ea neque ab quia esse debitis quae repellat, quidem vitae asperiores consectetur facilis.
                                                                                                                Ipsa a numquam, sunt vero pariatur alias voluptate dolor odit ullam id totam quibusdam rerum debitis cum veritatis molestias? Omnis nisi iure consequuntur nobis modi porro mollitia non accusamus error.
                                                                                                                Dicta incidunt vero veniam, magni dolores consectetur porro unde ipsa repellendus temporibus optio officiis vitae accusantium ducimus numquam ad! Impedit, consequatur maxime. Veritatis delectus quasi est nisi blanditiis nobis quibusdam.
                                                                                                                Sint fuga, pariatur, enim eligendi soluta quae eius unde nisi quis quisquam harum optio, nostrum cumque numquam consequuntur quibusdam necessitatibus. Beatae pariatur debitis, quibusdam officiis delectus incidunt culpa dicta omnis?
                                                                                                                Molestiae blanditiis porro sapiente ex illo quo possimus, rem ad incidunt aut dolorem deleniti iste qui dolorum accusantium optio adipisci sit excepturi nulla tempore mollitia, vero doloremque asperiores pariatur. Commodi!
                                                                                                                Ipsum id nihil ad labore doloribus dolores suscipit quas earum quos eveniet, esse nesciunt tenetur omnis a numquam vitae dicta exercitationem, iure vero cum recusandae! Ducimus nisi iure fuga odit.
                                                                                                                Beatae deserunt veritatis repellendus eligendi, repellat corporis ullam ratione excepturi animi facere reiciendis expedita, consectetur, ex ut doloremque! Autem nisi consectetur quidem! Ea, iste! Cumque dolore alias eos. Quo, magnam?
                                                                                                                Et reiciendis, consequatur accusamus eaque enim laboriosam voluptate neque qui quisquam dolores, officiis doloremque voluptas omnis tempore deleniti ducimus eius id iure minus. Consequuntur architecto tempore dolorum facilis doloribus labore.
                                                                                                                Quos saepe et sit culpa unde recusandae corporis quis aliquam expedita beatae. Et eos ut, sunt praesentium porro sint alias rerum eaque ullam tempora delectus mollitia! Quaerat cum molestias tempora!
                                                                                                                Magnam, molestias! Nostrum consectetur natus incidunt iure rem, debitis dolorem, ea enim autem recusandae, minus veritatis laboriosam quae. Voluptas minus pariatur in saepe velit? Impedit dolor autem maxime adipisci eveniet.
                                                                                                                Illum corrupti sed accusantium reiciendis quia dolorum similique dignissimos, mollitia nobis reprehenderit enim expedita suscipit fugiat eligendi quos fuga rerum totam! Expedita unde ducimus nihil velit quas labore laborum ut!
                                                                                                                Iste dolor corrupti tempora porro, qui assumenda explicabo, dicta, minima ipsa excepturi cumque ad eligendi suscipit repellendus culpa id facere illo distinctio quam! At fugiat ipsa voluptate soluta, aliquam dicta!
                                                                                                                Et eligendi molestias vitae hic cum perferendis doloremque ab, ex debitis omnis similique doloribus delectus quisquam? Eos ratione neque porro non illum ducimus voluptate quos vel. Veritatis maiores dolor expedita?
                                                                                                                Praesentium magni itaque enim sed deserunt, sunt voluptas quam suscipit soluta delectus laboriosam cumque, inventore, pariatur fuga? Dolores voluptatibus repellendus provident libero unde in! Dolores reiciendis voluptatem veniam officiis error!
                                                                                                                Asperiores, cumque. Iste, iusto accusantium quos sed, distinctio nemo fuga ab suscipit quaerat provident repellat corrupti voluptatum possimus ut repudiandae dolorem rerum recusandae dignissimos. Provident sapiente odio blanditiis quis dicta?
                                                                                                                Sint, libero a sit eos, quod optio veritatis non sapiente nulla incidunt, eum accusamus molestias illo ex nesciunt ullam ipsam repellendus corrupti doloribus consequuntur quo vero? Atque minus ut magnam?
                                                                                                                Deleniti architecto asperiores recusandae non aliquam itaque in. Sapiente doloribus minima soluta repellendus nulla pariatur laudantium, aliquam dolores, ab suscipit, provident fugiat impedit itaque tempore sint iure quibusdam adipisci. Aliquam.
                                                                                                                Voluptates asperiores corrupti nulla ea dolorum odit quisquam facilis quos quasi nam, nisi consequuntur! Ipsum, itaque consectetur doloremque quasi voluptate placeat reprehenderit magni odit distinctio. Nulla veritatis molestiae qui non?
                                                                                                                Saepe illum ipsam atque nesciunt fugit veritatis reprehenderit molestiae voluptatibus! Rerum maiores nesciunt possimus esse totam a ducimus tempore doloremque consectetur. Veritatis architecto ipsa autem cum mollitia nobis accusantium qui.
                                                                                                                Voluptatem libero sapiente perspiciatis odio neque cum inventore nemo, ullam voluptas perferendis dolorem illo, voluptates blanditiis maxime, illum repellendus veniam ipsum eligendi accusamus aut alias atque. Ab ipsum deserunt magni!
                                                                                                                Aspernatur, magnam corporis eligendi, adipisci dolorum expedita nostrum, cum perferendis maiores quasi culpa sunt dolore quas sequi blanditiis. Doloremque numquam ad eveniet commodi molestiae fuga distinctio laboriosam modi, maiores minus!
                                                                                                                Hic accusamus non iure eum laudantium nulla. Eveniet sapiente, omnis facilis porro sunt odit quam, molestiae assumenda dolores fugit voluptatem blanditiis veritatis a. Dignissimos ea quod reiciendis similique molestiae aliquid.
                                                                                                                Officiis est doloremque maxime ipsa pariatur! Fuga iusto officiis facilis numquam modi cumque unde dolore culpa nemo nam earum, nesciunt aspernatur vitae quisquam, labore dignissimos voluptatibus debitis laborum dolor. Eos.
                                                                                                                Laboriosam, ratione odio! In aliquid aspernatur assumenda neque vitae quibusdam, totam exercitationem esse cum dolore corrupti officia id, sunt iusto. Aut, dolores consequuntur blanditiis laboriosam quia excepturi vel sint nam!
                                                                                                                Assumenda magni eius non nemo architecto necessitatibus blanditiis ex enim deleniti ipsam incidunt harum, repudiandae asperiores sapiente unde porro iusto nostrum, pariatur adipisci exercitationem. Enim beatae quod culpa fugit non!
                                                                                                                Labore voluptatibus illum aliquam veritatis excepturi odit repellat? Fugit asperiores ipsam molestiae laborum quaerat suscipit fugiat rerum similique incidunt. Sapiente accusantium fugit blanditiis eum laborum earum officia repellat. Beatae, debitis.
                                                                                                                Molestiae, iusto, hic eos veniam, alias magnam sunt rem voluptate eum facilis neque perspiciatis atque deleniti sapiente voluptatem error eligendi itaque quos ipsa ducimus quasi blanditiis! Corporis perspiciatis impedit magnam?
                                                                                                                Perspiciatis eum sint quis fugit provident tempora soluta dolor eligendi autem maiores harum incidunt dolorem facilis tenetur alias quisquam recusandae aut temporibus id repellat, consequatur molestias nostrum? Voluptas, magnam eius.
                                                                                                                Itaque facilis magni error quaerat saepe aliquam incidunt labore, ex inventore veniam cum voluptatum minima, possimus dolor pariatur eveniet natus aperiam adipisci cupiditate eos vel eaque. Odio ipsum mollitia eius.
                                                                                                                Harum ducimus facere officiis ipsum accusantium error asperiores veniam fugiat! Totam rerum excepturi facere aspernatur magnam quo possimus quaerat id corporis assumenda, dolorum consequatur est et recusandae repellendus inventore. Soluta.
            </p>
        </div>
        <div className='Cart_Footer'></div>


    </div>)
}

export default Cart
